### ISSUE TITLE
GitHub command 

### ISSUE THREAD

**Issue by jaw0r3k** [discordjs/discord-toolkit-bot#10]
What about moving github command here ? + adding more things to find like comments
![image](https://user-images.githubusercontent.com/76836550/202261739-3e28354b-ed36-49c2-9371-afecc79e4bf3.png)
****

**Comment by jaw0r3k** [comment]
@almostSouji  ?

**Comment by almostSouji** [comment]
That worker's existence is more a token of negligence than it being useful
