### ISSUE TITLE
Token detector

### ISSUE THREAD

**Issue by Syjalo** [discordjs/discord-toolkit-bot#13]
The bot will look at the content of messages (Maybe the content of files too) and look for tokens. If it finds a token, then it will publish that token to GitHub Gist to be invalided by Discord.

**Comment by jaw0r3k** [comment]
nice idea
however most times tokens are in images

**Comment by jaw0r3k** [comment]
discord remainds you when sending token in a message
but not in a file
and to check files you have to fetch them
![image](https://user-images.githubusercontent.com/76836550/212483037-e903bea9-b2c3-4971-bcee-17efd9291fc8.png)

**Comment by almostSouji** [comment]
One would think people care about this message - alas they don't do so in all cases (we have a flagging mechanism in place at the moment)
Considerable are the following options:

1.  Implement into moderation flow (potentially with automated action, if author is not token owner)
1. I have suggested Discord implement this natively for public servers/channels (has not received any traction, though)
1. Drop the feature (the flag trips rarely enough to make this a valid option)

In any case, I don't see this happening on toolkit for now
